# device = "/dev/input/event9"

# DISABLED    0
# BTN_LEFT		272
# BTN_RIGHT		273
# BTN_MIDDLE	274
# BTN_SIDE		275
# BTN_EXTRA		276
free_spin_button = 273

damping = 3.1

min_deceleration = 1420

max_deceleration = 6000

initial_speed = 600.0

speed_factor = 40.0

use_braking = true

braking_dejitter_microseconds = 100000

max_braking_times = 3

use_mouse_movement_braking = true

# advanced

tick_interval_microseconds = 2000

min_speed = 0

speed_smooth_window_microseconds = 200000

max_speed_change_lowerbound = 512

min_speed_change_upperbound = 1024

min_speed_change_ratio = 0.0625

max_speed_change_ratio = 1

braking_cut_off_speed = 1000.0

speed_decrease_per_braking = inf

mouse_movement_dejitter_distance = 200

max_mouse_movement_event_interval_microseconds = 50000

mouse_movement_braking_cut_off_speed = 200

speed_decrease_per_mouse_movement = inf
